package robinlb99.tienda.igu.VerStockProductos;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import robinlb99.tienda.igu.Window;
import robinlb99.tienda.logica.LogicController;
import robinlb99.tienda.logica.Producto;

public class VerStock extends javax.swing.JFrame {
    
    LogicController control = new LogicController();
    Window ventana = new Window();
    
    ArrayList<Producto> productos = null;

    /**
     * Creates new form VerStock
     */
    public VerStock() {
        initComponents();
        
        productos = control.listaProductos();
        cargarTabla(false, 0);
        
        
        btnFiltrar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (!txtFiltroNombre.getText().isBlank()) {
                    
                    productos = control.listaProductos();
                    
                    long idFiltrar = 0;
                    
                    for (Producto prod : productos) {
                        if (prod.getNombre().toLowerCase().equals(txtFiltroNombre.getText().toLowerCase())) {
                            idFiltrar = prod.getId();
                            break;
                        }
                    }
                    
                    cargarTabla(true, idFiltrar);
                    btnBorrarFiltro.setEnabled(true);
                    
                } else {
                    
                    ventana.mensaje("Error", "error", "El campo filtro esta vacio.");
                    
                }
            }
        });
        
        
        btnBorrarFiltro.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                cargarTabla(false, 0);
                btnBorrarFiltro.setEnabled(false);
            }
            
        });
        
        
        btnModificarProducto.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (dataTable.getSelectedRow() != -1) {
                    
                    long id =  Long.parseLong(dataTable.getValueAt(dataTable.getSelectedRow(), 0).toString());
                    
                    dispose();
                    ventana.modificarProducto(id);
                    
                } else {
                    ventana.mensaje("Error", "error", "No se selecciono un registro.");
                }
            }
            
        });
        
        
        btnMasUnidades.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                
                if (dataTable.getSelectedRow() != -1) {
                    
                    long id = Long.parseLong(dataTable.getValueAt(dataTable.getSelectedRow(), 0).toString());
                    dispose();
                    ventana.agregarUnidadesProducto(id);
                    
                } else {
                    ventana.mensaje("Advertencia", "warning", "No se selecciono ningún registro.");
                }
                
            }
             
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFiltroNombre = new javax.swing.JTextField();
        btnFiltrar = new javax.swing.JButton();
        btnBorrarFiltro = new javax.swing.JButton();
        btnMasUnidades = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnIngresarNuevoProducto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        btnModificarProducto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Inventario de productos");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/buscar-24px.png"))); // NOI18N
        jLabel2.setText("Filtrar por nombre:");
        jLabel2.setMaximumSize(new java.awt.Dimension(147, 36));
        jLabel2.setMinimumSize(new java.awt.Dimension(147, 36));
        jLabel2.setPreferredSize(new java.awt.Dimension(147, 36));

        txtFiltroNombre.setMaximumSize(new java.awt.Dimension(68, 36));
        txtFiltroNombre.setMinimumSize(new java.awt.Dimension(68, 36));
        txtFiltroNombre.setPreferredSize(new java.awt.Dimension(68, 36));
        txtFiltroNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFiltroNombreActionPerformed(evt);
            }
        });

        btnFiltrar.setText("Filtrar");
        btnFiltrar.setMaximumSize(new java.awt.Dimension(76, 36));
        btnFiltrar.setMinimumSize(new java.awt.Dimension(76, 36));
        btnFiltrar.setPreferredSize(new java.awt.Dimension(76, 36));

        btnBorrarFiltro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/borrar-24px.png"))); // NOI18N
        btnBorrarFiltro.setText("Borrar filtro");
        btnBorrarFiltro.setEnabled(false);
        btnBorrarFiltro.setMaximumSize(new java.awt.Dimension(124, 36));
        btnBorrarFiltro.setMinimumSize(new java.awt.Dimension(124, 36));
        btnBorrarFiltro.setPreferredSize(new java.awt.Dimension(124, 36));

        btnMasUnidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/mas.png"))); // NOI18N
        btnMasUnidades.setText("Agregar unidades");
        btnMasUnidades.setIconTextGap(8);
        btnMasUnidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasUnidadesActionPerformed(evt);
            }
        });

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/deshacer-16px.png"))); // NOI18N
        btnAtras.setText("Atras");
        btnAtras.setIconTextGap(10);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnIngresarNuevoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nuevo-documento.png"))); // NOI18N
        btnIngresarNuevoProducto.setText("Nuevo producto");
        btnIngresarNuevoProducto.setIconTextGap(8);
        btnIngresarNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarNuevoProductoActionPerformed(evt);
            }
        });

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(dataTable);

        btnModificarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/editar-16px.png"))); // NOI18N
        btnModificarProducto.setText("Modificar registro");
        btnModificarProducto.setIconTextGap(8);
        btnModificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnIngresarNuevoProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificarProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMasUnidades)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFiltroNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBorrarFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 364, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrarFiltro, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(txtFiltroNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFiltrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMasUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIngresarNuevoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFiltroNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiltroNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFiltroNombreActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        this.dispose();
        ventana.menu();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnMasUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasUnidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMasUnidadesActionPerformed

    private void btnIngresarNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarNuevoProductoActionPerformed
        this.dispose();
        ventana.nuevoProducto("", 0, 0);
    }//GEN-LAST:event_btnIngresarNuevoProductoActionPerformed

    private void btnModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarProductoActionPerformed
    
    
    private void cargarTabla(boolean filtrar, long id) {
        // Definir modelo de tabla
        DefaultTableModel tablaModel = new DefaultTableModel() {
            // Filas y columnas no editables.
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        // Establecer los nombres de las columnas
        String titulos[] = {"ID", "Nombre", "Precio", "Unidades disponibles"};
        tablaModel.setColumnIdentifiers(titulos);

        if (filtrar) {
            
            if (id == 0) {
                
                ventana.mensaje("Registro no encontrado", "warning", "El registro que usted esta buscando no se encontro\nVerifique que haya ingresado correctamente el dato.");
                txtFiltroNombre.grabFocus();
                
            } else {
                
                Producto prod = control.buscarProducto(id);
                Object[] objeto = {prod.getId(), prod.getNombre(), prod.getPrecio(), prod.getStock()};
                tablaModel.addRow(objeto);
                
            }
            
        } else {
            // Recorrer datos y mostrarlos
            if (productos != null) {
                for (Producto producto : productos) {

                    Object[] objeto = {producto.getId(), producto.getNombre(), producto.getPrecio(), producto.getStock()};
                    tablaModel.addRow(objeto);

                }
            }
        }

        dataTable.setModel(tablaModel);

    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBorrarFiltro;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnIngresarNuevoProducto;
    private javax.swing.JButton btnMasUnidades;
    private javax.swing.JButton btnModificarProducto;
    private javax.swing.JTable dataTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtFiltroNombre;
    // End of variables declaration//GEN-END:variables
}
